#!/bin/bash

VERSION=$1
DIR=$(dirname $0)

if [[ -z "$VERSION" ]]; then
  echo "Needs a version"
  exit 1
fi
SCHEME_NAME="<%= name %>"
ARCHIVE_NAME="<%= name.toLowerCase() %>-$VERSION"
PROVISIONING_PROFILE="<%= name %> Test"

. $DIR/build
cd platforms/ios
xcodebuild archive -scheme $SCHEME_NAME -archivePath $ARCHIVE_NAME
xcodebuild -exportArchive -archivePath $ARCHIVE_NAME.xcarchive -exportPath $ARCHIVE_NAME -exportFormat ipa -exportProvisioningProfile "$PROVISIONING_PROFILE"
